import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 32,
    maxHeight: '92%',
  },
  loadingContainer: {
    paddingVertical: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: '#6F759B',
  },
  sheetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  sheetTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#1D2A74',
  },
  closeButton: {
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sheetContent: {
    paddingBottom: 12,
  },
  field: {
    marginBottom: 16,
  },
  fieldLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1D2A74',
    marginBottom: 8,
  },
  inputBox: {
    backgroundColor: '#F0F1FA',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  inputBoxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F0F1FA',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  textInput: {
    flex: 1,
    fontSize: 15,
    color: '#1D2A74',
  },
  placeholderText: {
    color: '#8F96B0',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1D2A74',
  },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1E592D',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 20,
  },
  addButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
    marginLeft: 6,
    fontSize: 13,
  },
  modalAddButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2C6D2F',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 20,
    alignSelf: 'flex-start',
    marginBottom: 16,
  },
  tableCard: {
    backgroundColor: '#F8F9FF',
    borderRadius: 22,
    overflow: 'hidden',
    marginBottom: 20,
  },
  tableHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EEF0FF',
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  tableHeaderText: {
    flex: 1,
    color: '#6D7396',
    fontWeight: '700',
    fontSize: 12,
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#EEF0FF',
    gap: 6,
  },
  cellInput: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 10,
    fontSize: 13,
    color: '#1D2A74',
  },
  rowActions: {
    width: 68,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 4,
  },
  rowActionBtn: {
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: '#F0F1FA',
    justifyContent: 'center',
    alignItems: 'center',
  },
  tableFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EEF0FF',
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  footerLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1D2A74',
  },
  footerValue: {
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
    color: '#1D2A74',
  },
  summaryRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  summaryBox: {
    flex: 1,
    backgroundColor: '#F0F1FA',
    borderRadius: 20,
    padding: 16,
    alignItems: 'center',
  },
  summaryBoxGreen: {
    backgroundColor: '#E5F8E8',
  },
  summaryLabel: {
    color: '#6F759B',
    fontSize: 13,
    marginBottom: 6,
  },
  summaryAmount: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1D2A74',
  },
  errorText: {
    color: '#E43A3A',
    fontSize: 13,
    textAlign: 'center',
    marginBottom: 12,
  },
  saveButton: {
    backgroundColor: '#1D2A74',
    borderRadius: 24,
    paddingVertical: 16,
    alignItems: 'center',
    marginBottom: 12,
  },
  saveButtonDisabled: {
    backgroundColor: '#8A92B8',
  },
  buttonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  cancelButton: {
    alignItems: 'center',
    paddingVertical: 12,
  },
  cancelText: {
    color: '#1D2A74',
    fontSize: 15,
    fontWeight: '700',
  },
  infoBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    backgroundColor: '#F3F5FF',
    borderRadius: 18,
    padding: 14,
    marginBottom: 18,
  },
  infoText: {
    color: '#4B5478',
    fontSize: 13,
    lineHeight: 20,
    flex: 1,
  },
  modalFooter: {
    flexDirection: 'row',
    gap: 12,
  },
  modalCancelButton: {
    flex: 1,
    paddingVertical: 14,
    alignItems: 'center',
    borderRadius: 20,
    backgroundColor: '#F5F7FF',
  },
  modalCancelText: {
    color: '#1D2A74',
    fontSize: 15,
    fontWeight: '700',
  },
  modalConfirmButton: {
    flex: 1,
    paddingVertical: 14,
    alignItems: 'center',
    borderRadius: 20,
    backgroundColor: '#1D2A74',
  },
  modalConfirmText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
});
