import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FF',
  },
  keyboardView: {
    flex: 1,
  },
  inner: {
    flex: 1,
    paddingHorizontal: 24,
    justifyContent: 'center',
  },
  brandArea: {
    alignItems: 'center',
    marginBottom: 40,
  },
  brandTitle: {
    fontSize: 42,
    fontWeight: '800',
    color: '#2E3192',
    letterSpacing: 3,
  },
  brandSubtitle: {
    fontSize: 16,
    color: '#6F759B',
    marginTop: 6,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 24,
    padding: 24,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: {width: 0, height: 6},
    elevation: 6,
    marginBottom: 24,
  },
  cardTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#17173C',
    marginBottom: 6,
  },
  cardSubtitle: {
    fontSize: 14,
    color: '#6F759B',
    marginBottom: 24,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F4F7FC',
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#E4E9F5',
    paddingHorizontal: 14,
    marginBottom: 6,
  },
  inputIcon: {
    marginRight: 8,
  },
  input: {
    flex: 1,
    paddingVertical: 14,
    fontSize: 16,
    color: '#17173C',
  },
  inputError: {
    borderColor: '#FF4444',
  },
  error: {
    color: '#FF4444',
    fontSize: 12,
    marginBottom: 12,
    marginLeft: 4,
  },
  button: {
    backgroundColor: '#2E3192',
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 18,
    elevation: 4,
    shadowColor: '#2E3192',
    shadowOpacity: 0.35,
    shadowRadius: 8,
    shadowOffset: {width: 0, height: 4},
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  footer: {
    alignItems: 'center',
    marginBottom: 16,
  },
  footerText: {
    fontSize: 15,
    color: '#6F759B',
  },
  footerLink: {
    color: '#2E3192',
    fontWeight: '700',
  },
  betaText: {
    textAlign: 'center',
    fontSize: 12,
    color: '#B0B8D0',
    fontStyle: 'italic',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 24,
    paddingBottom: 36,
    paddingTop: 12,
    elevation: 20,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: -4},
    shadowOpacity: 0.12,
    shadowRadius: 12,
  },
  modalHandle: {
    width: 44,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#DDE3EC',
    alignSelf: 'center',
    marginBottom: 20,
  },
  modalIconWrapper: {
    alignSelf: 'center',
    backgroundColor: '#EEF2FF',
    borderRadius: 50,
    width: 64,
    height: 64,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 14,
  },
  modalIcon: {
    fontSize: 28,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#17173C',
    textAlign: 'center',
    marginBottom: 6,
  },
  modalHint: {
    fontSize: 14,
    color: '#6F759B',
    textAlign: 'center',
    marginBottom: 22,
  },
  modalInputWrapper: {
    position: 'relative',
    width: '100%',
    marginBottom: 6,
  },
  modalInput: {
    width: '100%',
    paddingVertical: 14,
    paddingHorizontal: 16,
    paddingRight: 44,
    backgroundColor: '#F4F7FC',
    borderRadius: 14,
    fontSize: 16,
    color: '#17173C',
    borderWidth: 1.5,
    borderColor: '#E4E9F5',
  },
  clearButton: {
    position: 'absolute',
    right: 14,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    padding: 4,
  },
  clearButtonText: {
    fontSize: 14,
    color: '#A0A8C0',
    fontWeight: '600',
  },
  errorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
    marginLeft: 2,
  },
  errorIcon: {
    fontSize: 12,
    marginRight: 4,
  },
  modalButton: {
    backgroundColor: '#2E3192',
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 18,
    elevation: 4,
    shadowColor: '#2E3192',
    shadowOpacity: 0.35,
    shadowRadius: 8,
    shadowOffset: {width: 0, height: 4},
  },
  modalCancelButton: {
    marginTop: 12,
    alignItems: 'center',
    padding: 10,
  },
  modalCancelText: {
    color: '#A0A8C0',
    fontSize: 15,
    fontWeight: '500',
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 16,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#E8EDF5',
  },
  dividerText: {
    marginHorizontal: 10,
    fontSize: 12,
    color: '#A0A8C0',
    fontWeight: '500',
  },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  contactCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#EEF2FF',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: '#C7D0F0',
  },
  contactCardLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  contactIcon: {
    fontSize: 20,
    marginRight: 10,
  },
  contactLabel: {
    fontSize: 13,
    color: '#6F759B',
    marginBottom: 2,
  },
  contactNumber: {
    fontSize: 17,
    fontWeight: '700',
    color: '#2E3192',
    letterSpacing: 0.5,
  },
  contactArrow: {
    fontSize: 26,
    color: '#2E3192',
    fontWeight: '300',
  },
});
