import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: '#F6F7FF',
  },
  countRow: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 8,
  },
  countText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#6F759B',
  },
  listContent: {
    paddingHorizontal: 16,
    paddingBottom: 100,
  },
  saleCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#B3B7D5',
    shadowOpacity: 0.12,
    shadowRadius: 14,
    shadowOffset: {width: 0, height: 4},
    elevation: 3,
  },
  saleCardLeft: {
    flex: 1,
  },
  saleCustomer: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1D2A74',
    marginBottom: 4,
  },
  saleDate: {
    fontSize: 12,
    color: '#8A92B8',
    marginBottom: 8,
  },
  salePaidPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EDF7F1',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 4,
    alignSelf: 'flex-start',
  },
  salePaidLabel: {
    fontSize: 11,
    color: '#8A92B8',
    marginRight: 4,
  },
  salePaidValue: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1B792E',
  },
  saleCardActions: {
    flexDirection: 'column',
    alignItems: 'center',
  },
  viewBtn: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: '#EEF0FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  deleteBtn: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: '#FCE8E8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  editBtn: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: '#EEF0FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 20,
    paddingBottom: 32,
    maxHeight: '95%',
  },
  sheetHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#E0E3F0',
    borderRadius: 2,
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 16,
  },
  sheetTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1D2A74',
    marginBottom: 18,
  },
  formSection: {
    marginBottom: 22,
  },
  formLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: '#23283A',
    marginBottom: 12,
  },
  smallLabel: {
    fontSize: 14,
    color: '#34384A',
    marginBottom: 8,
  },
  sellerInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sellerInputBox: {
    flex: 1,
    height: 64,
    borderRadius: 14,
    backgroundColor: '#E7E3EC',
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 10,
  },
  sellerPickerWrap: {
    flex: 1,
  },
  sellerPicker: {
    color: '#23283A',
    marginLeft: 8,
  },
  addSellerIconBtn: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: '#EEF0FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectionCard: {
    borderRadius: 18,
    backgroundColor: '#F2EEF7',
    padding: 14,
  },
  productSearchBox: {
    height: 44,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  productSearchInput: {
    flex: 1,
    marginLeft: 8,
    fontSize: 15,
    color: '#23283A',
  },
  emptyStateText: {
    fontSize: 14,
    color: '#75798B',
    textAlign: 'center',
    paddingVertical: 12,
  },
  productRow: {
    minHeight: 58,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    paddingHorizontal: 14,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  productRowActive: {
    borderWidth: 1.5,
    borderColor: '#C9CEFF',
  },
  productLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: 10,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: '#B9B8C8',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  checkboxActive: {
    backgroundColor: '#1B238B',
    borderColor: '#1B238B',
  },
  productName: {
    fontSize: 15,
    color: '#23283A',
    marginLeft: 10,
  },
  productPrice: {
    fontSize: 13,
    color: '#6D7286',
  },
  qtyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 10,
    marginTop: -4,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderTopWidth: 1,
    borderTopColor: '#EDE9F4',
  },
  qtyIcon: {
    marginRight: 8,
  },
  qtyInput: {
    flex: 1,
    fontSize: 15,
    color: '#23283A',
  },
  qtyUnit: {
    fontSize: 13,
    color: '#8A92B8',
    marginLeft: 8,
  },
  paymentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  paymentButton: {
    width: '47%',
    height: 68,
    borderRadius: 16,
    backgroundColor: '#E7E3EC',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  paymentButtonActive: {
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#101A79',
  },
  paymentText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#4B4E60',
    marginLeft: 8,
  },
  paymentTextActive: {
    fontSize: 16,
    fontWeight: '800',
    color: '#101A79',
    marginLeft: 8,
  },
  summaryBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    backgroundColor: '#EEF1FF',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 20,
  },
  summaryLabel: {
    fontSize: 14,
    color: '#51608C',
    marginRight: 6,
  },
  summaryValue: {
    fontSize: 15,
    fontWeight: '800',
    color: '#101A79',
    marginRight: 16,
  },
  divider: {
    height: 1,
    backgroundColor: '#F0ECF5',
    marginBottom: 20,
  },
  infoTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  infoTitle: {
    marginLeft: 8,
    fontSize: 17,
    fontWeight: '800',
    color: '#101A79',
  },
  textInput: {
    height: 58,
    borderRadius: 14,
    backgroundColor: '#E7E3EC',
    paddingHorizontal: 18,
    color: '#23283A',
    fontSize: 16,
    marginBottom: 16,
  },
  textInputDisabled: {
    opacity: 0.5,
  },
  submitButton: {
    height: 72,
    borderRadius: 16,
    backgroundColor: '#191E8D',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#191E8D',
    shadowOpacity: 0.3,
    shadowRadius: 14,
    shadowOffset: {width: 0, height: 8},
    elevation: 6,
    marginBottom: 4,
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  submitIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  submitText: {
    fontSize: 18,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  sheetActions: {
    flexDirection: 'row',
    marginTop: 16,
    marginBottom: 8,
  },
  cancelBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 20,
    backgroundColor: '#F5F7FF',
    alignItems: 'center',
    marginRight: 8,
  },
  cancelBtnFull: {
    paddingVertical: 14,
    borderRadius: 20,
    backgroundColor: '#F5F7FF',
    alignItems: 'center',
  },
  cancelBtnText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#6F759B',
  },
  saveBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 20,
    backgroundColor: '#1D2A74',
    alignItems: 'center',
  },
  saveBtnText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  errorText: {
    color: '#E43A3A',
    fontSize: 12,
    marginTop: 4,
  },
  centeredLoader: {
    alignItems: 'center',
    paddingVertical: 48,
  },
  loaderText: {
    marginTop: 12,
    fontSize: 14,
    color: '#6F759B',
  },
  emptyNotice: {
    alignItems: 'center',
    paddingVertical: 24,
  },
  emptyNoticeText: {
    fontSize: 14,
    color: '#E43A3A',
    textAlign: 'center',
    marginVertical: 12,
    lineHeight: 22,
  },
  tabRow: {
    flexDirection: 'row',
    backgroundColor: '#F0F0FB',
    borderRadius: 24,
    padding: 6,
    marginBottom: 16,
  },
  tabBtn: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 20,
  },
  tabBtnActive: {
    backgroundColor: '#FFFFFF',
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: {width: 0, height: 2},
  },
  tabText: {
    fontSize: 14,
    color: '#8A92B8',
    fontWeight: '600',
  },
  tabTextActive: {
    color: '#1D2A74',
    fontWeight: '700',
  },
  sellerList: {
    maxHeight: 280,
  },
  sellerRow: {
    backgroundColor: '#F8F9FF',
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
  },
  sellerViewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sellerEditRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sellerName: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1D2A74',
    flex: 1,
  },
  sellerBtns: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  detailSection: {
    backgroundColor: '#F8F9FF',
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
  },
  detailSectionTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1D2A74',
    marginBottom: 12,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#EEF0FF',
  },
  detailLabel: {
    fontSize: 14,
    color: '#6F759B',
  },
  detailValue: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1D2A74',
  },
  productTableHeader: {
    flexDirection: 'row',
    backgroundColor: '#EEF0FF',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 4,
  },
  productTableCell: {
    fontSize: 12,
    fontWeight: '800',
    color: '#1D2A74',
  },
  productTableRow: {
    flexDirection: 'row',
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 6,
    marginBottom: 2,
  },
  productTableValue: {
    fontSize: 13,
    color: '#22263F',
  },
});
